@startuml
component start
component end
sr -- KF
OO -- vy
start -- FP
FP -- end
vy -- mi
vy -- KF
na -- vy
start -- sr
FP -- lh
sr -- FP
na -- FP
KF -- end
na -- mi
lh -- KF
lh -- end
start -- na
wp -- KF
mi -- KF
sr -- vy
vy -- lh
sr -- mi
@enduml